[package]
name = "static_number_analyzer"
version = "0.1.0"
authors = ["Felix Schütt <felix.schuett@maps4print.com>"]

[dependencies]
syn = { version = "0.14.2", features = ["full", "extra-traits"] }
quote = "0.6.3"